<?php

namespace CreateThemesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FooterthemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FooterthemeRepository extends EntityRepository
{
}
