<?php

namespace CreateThemesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HeaderThemesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeaderThemesRepository extends EntityRepository
{
}
